g=read.graph("C:\\Users\\proshant\\Desktop\\20July14\\DRCN.net",format="pajek")
d=degree(g)
b=betweenness(g)
t=transitivity(g,type="local",vids=V(g))
c=closeness(g,vids=V(g))
e=evcent(g)
p=page.rank(g)

write.table(x=d,"C:\\Users\\proshant\\Desktop\\20July14\\degree.csv",sep = ",")
write.table(x=b,"C:\\Users\\proshant\\Desktop\\20July14\\betweenness.csv",sep = ",")
write.table(x=t,"C:\\Users\\proshant\\Desktop\\20July14\\transitivity.csv",sep = ",")
write.table(x=c,"C:\\Users\\proshant\\Desktop\\20July14\\closeness.csv",sep = ",")
write.table(x=e$vector,"C:\\Users\\proshant\\Desktop\\20July14\\eigen.csv",sep = ",")
write.table(x=p$vector,"C:\\Users\\proshant\\Desktop\\20July14\\page.csv",sep = ",")

